### ISSUE TITLE
other USBaspLoader repos - are you interested in merge?

### ISSUE THREAD

**Issue by baerwolf** [embedded-creations/USBaspLoader-tiny85#4]
Hi embedded-creations,

For some time now I enhanced the original obdev 2010-07-27 USBaspLoader.

Till today I added lots of bugfixes and some new features.
For example it is now possible to read FUSE and LOCKbits. Now, the bootloader also is enabled to be updated via its USB interface. (No ISP needed)

The complete and most recent sourcecode can be found and obtained at https://github.com/baerwolf/USBaspLoader (https://github.com/baerwolf/USBaspLoader.git).

Because you are also hosting an USBaspLoader repository I just want to make you aware of this and I thought we might want to merge our souces?

I really would very happy if you look into it and try the new features ;-)...

Thank you a lot and best regards,

-Stephan Bärwolf

**Comment by embedded-creations** [comment]
Hi Stephan,

Thanks for the heads up, I wasn't aware of your work before.  Next time I work on my branch I'll take a look at your modifications.  Of course, feel free to merge anything in my sources into yours.

Thanks,
Louis

On Sep 18, 2012, at 7:11 AM, Stephan Baerwolf <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi embedded-creations,

For some time now I enhanced the original obdev 2010-07-27 USBaspLoader.

Till today I added lots of bugfixes and some new features.
For example it is now possible to read FUSE and LOCKbits. Now, the bootloader also is enabled to be updated via its USB interface. (No ISP needed)

The complete and most recent sourcecode can be found and obtained at https://github.com/baerwolf/USBaspLoader (https://github.com/baerwolf/USBaspLoader.git).

Because you are also hosting an USBaspLoader repository I just want to make you aware of this and I thought we might want to merge our souces?

I really would very happy if you look into it and try the new features ;-)...

Thank you a lot and best regards,

-Stephan Bärwolf
